bottom_right:
  x: 108
  y: 72
columns: 12
first_probe: A1
last_probe: B12
FA_wash:
  x: 20
  y: 119
  z: -37
rows: 8
sequence:
- probe: wp
- pause: 2
- pump: 30
- pause: 300
- probe: FA_wash
- pause: 2
- pump: 30
- probe: wp
- pause: 2
- pump: 30
- image: 1
top_left:
  x: 0
  y: 0
well_spacing: 9
z_base: -36
num_cycles: 1
pump_COM: COM6
stage_COM: COM5
