input_folder: M:\ChromatinTeam\Images_processing\20200604_Exp328_KSB_Elyra_tracing_myc_D1-10_v2\02_DECON
output_folder: M:\ChromatinTeam\Images_processing\20200604_Exp328_KSB_Elyra_tracing_myc_D1-10_v2\04_Analysis
dc_image_folder: M:\ChromatinTeam\Images_processing\20200604_Exp328_KSB_Elyra_tracing_myc_D1-10_v2\03_DC
output_file_prefix: 20200604_Exp328v2_KSB_Elyra_tracing_myc_D1-10_MLE_

image_filetype: 
    - '.h5'
image_template: 
    - 'DE_2'
    - 'W0001'
dc_image_scaling: 0.5

#Camera properties
xy_nm: 97
z_nm: 200

#Fiducial parameters (NB! 0-based, also the timepoints):
bead_ch: 0
bead_reference_timepoint : 13
bead_threshold: 5000
min_bead_intensity: 10000
bead_points: 20

#Tracing parameters (NB! 0-based, also the timepoints):
# fit_func can be LS or MLE.
trace_ch: 1
ref_slice: 13
spot_threshold: 10000
fit_func: MLE

roi_image_size:
    - 16
    - 32
    - 32
    
# PARAMETERS BELOW ARE ONLY FOR ANALYSIS POST TRACING      #
# -------------------------------------------------------- #
#Tracing QC parameters, need to be empirically determined for a setup.
A_to_BG: 5
sigma_xy_max: 120
sigma_z_max: 300

#List of traces manually excluded (-1 indicated no exclusions):
man_qc_trace_id:
    - -1

#List of frame contents, those labeled "blank", "all" or "_rep" can be excluded in the analysis.
frame_name:
    - pre_image
    - E01
    - E02
    - E03
    - E04
    - E05
    - E06
    - E07
    - E08
    - E09
    - E10
    - E01_rep
    - blank
    - all
