# conda env create|update -f environment.yml
name: pychrtrace
dependencies:
    - python=3.8
    - dask
    - joblib
    - pandas
    - numpy
    - scipy
    - scikit-image
    - zarr
    - plotly
    - matplotlib
    - nbformat
    - ipykernel
    - nb_conda
    - pip
    - pip:
        - napari[all]
        - cellpose
        - pyyaml
        - czifile
        - PySimpleGUI
        - aicsimageio
        - imreg_dft
        - seaborn
        - flowdec[tf_gpu]