# conda env create | update -f environment.yml
name: looptrace
dependencies:
    - python=3.9
    - numba::numba
    - numba::llvmlite
    - scipy
    - pandas
    - dask
    - joblib
    - jupyter
    - nb_conda
    - pip
    - pip:
        - scikit-image
        - pyyaml
        - zarr
        - fsspec>=0.9.0
        - imagecodecs
        - napari
        - numcodecs
        - tqdm
        - cellpose
        - nd2