# conda env create | update -f environment.yml
name: looptrace
dependencies:
    - python=3.8
    - scipy
    - dask
    - numba
    - joblib
    - plotly
    - nbformat
    - ipykernel
    - nb_conda
    - pip
    - pip:
        - scikit-image
        - napari[all]
        - cellpose
        - pyyaml
        - PySimpleGUI
        - imreg_dft
        - czifile
        - seaborn
        - zarr
        - fsspec>=0.9.0
        
