# conda env create | update -f environment.yaml
name: looptrace
channels:
    - conda-forge
    - defaults
    - numba
dependencies:
    - pandas
    - python
    - numba
    - llvmlite
    - scipy
    - numpy
    - pandas
    - dask
    - joblib
    - jupyterlab=3.4.0    
      # due to https://github.com/jupyterhub/jupyterhub/pull/4039
    - jupyterhub-singleuser = 2.3.0
    - nb_conda
    - pip
    - pip:
        - tensorflow
        - batchspawner == 1.1.0
        - scikit-image
        - pyyaml
        - zarr
          # for deconvolution
        - flowdec
        - fsspec >= 0.9.0
        - imagecodecs
        - napari
        - numcodecs
        - tqdm
        - cellpose
        - nd2
