# conda env create | update -f environment.yml
name: looptrace
dependencies:
    - python=3.8
    - scipy
    - dask
    - numba
    - joblib
    - plotly 
    - nbformat 
    - ipykernel 
    - nb_conda
    - pip
    - pip:
        - scikit-image
        - pyyaml
        - seaborn
        - pyserial
        - PySimpleGUI
        - czifile
        - imreg_dft
        - zarr
        - napari[all]
        - fsspec>=0.9.0