[tool.poetry]
name = "looptrace"
version = "0.3dev"
description = "Library and programs for tracing chromatin loops from microscopy images"
authors = [
    "Kai Sandvold Beckwith",
    "Vince Reuter <vince.reuter@gmail.com>",
]
readme = "README.md"
license = "MIT"
repository = "https://github.com/gerlichlab/looptrace"
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Bioinformatics",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
# These are the main runtime dependencies.
python = ">= 3.10.0, < 3.12"
dask = "^2023.5.1"
logmuse = "^0.2.1"
numcodecs = "^0.11.0"
numpy = "^1.24.2"
matplotlib = { version = "^3.7.0", optional = true }
nd2 = { version = "^0.5.3", optional = true }
numba = { version = "^0.57.0", optional = true }
pandas = "^1.5.3"
piper = { version = "0.13.0", optional = true }
pyyaml = "^6.0"
scipy = "^1.10.1"
scikit-image = "^0.20.0"
seaborn = { version = "^0.12.0", optional = true }
tifffile = { version = "^2023.4.12", optional = true }
tqdm = "^4.65.0"
zarr = "^2.4.12"

[tool.poetry.extras]
analysis = ["matplotlib", "numba", "seaborn"]
dev = ["matplotlib", "nd2", "numba", "seaborn", "tifffile"]
pipeline = ["piper"]
polymer = ["numba"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
