#General settings
output_folder: M:\ChromatinTeam\Images_processing\20200604_Exp328_KSB_Elyra_tracing_myc_D1-10_v2\02_DC
output_name: 20200604_328_tracing_D1_D10_v2_
filetype: 
    - '.czi'
tags:
    - 'Title'
    - 'SizeX'
    - 'SizeY'
    - 'SizeZ'
    - 'SizeC'
    - 'SizeS'
    - 'Model'
    - 'System'
    - 'ScalingX'
    - 'ScalingY'
    - 'ScalingZ'

#Settings for merging and alignment and tracing functions.
folders:
    - 
    - 
template:
    -
course_ch: 1
fine_ch: -1

#Settings for nuclear segmentation.   
nuc_ch: 1
min_nuc_vol: 100000
nuc_exp_bb:
    - 29
    - 300
    - 300

#Settings for comparison functions
plot_ssim: 0
threshold_comparison: 1
comp_folder_1: M:\ChromatinTeam\Images_processing\20200528_OO_332_TADhoechst_Fixed_FISHed_FA-vs-H1FA50_ibidi-2\01_MyPiC
comp_folder_2: M:\ChromatinTeam\Images_processing\20200531_OO_332_TADhoechst_Fixed_FISHed_FA-vs-H1FA50_ibidi-2_afterFISH\01_MyPiC_repeat
template_comp_1: 
    - 'DE_2'
template_comp_2: 
    - 'DE_3'
analysis_channels:
    - 0
    - 1

#Settings for SR analysis
const_gauss_sigma: 20
cam_px: 512
cam_nm: 103
clip: 2
grid_px_size: 10
output_res: 4096
dbscan_eps: 200
dbscan_mins: 100