#General settings
output_folder: M:\ChromatinTeam\Images_processing\20200526_Exp326_KSB_Elyra_DAPI_TADs_SIM_Live_fix_perm_HCl\Comparisons\Ibidi_2\Live_vs_fixed
output_name: 326_SIM_Live_vs_Fixed_
filetype: 
    - '.czi'
tags:
    - 'Title'
    - 'SizeX'
    - 'SizeY'
    - 'SizeZ'
    - 'SizeC'
    - 'SizeS'
    - 'Model'
    - 'System'
    - 'ScalingX'
    - 'ScalingY'
    - 'ScalingZ'

#Settings for merging and alignment and tracing functions.
folders:
    - 
    - 
template:
    -
course_ch: 1
fine_ch: -1

#Settings for nuclear segmentation.   
nuc_ch: 1
min_nuc_vol: 100000
nuc_exp_bb:
    - 29
    - 300
    - 300

#Settings for comparison functions
threshold_comparison: 0
comp_folder_1: M:\ChromatinTeam\Images_processing\20200526_Exp326_KSB_Elyra_DAPI_TADs_SIM_Live_fix_perm_HCl\Ibidi_2_SIM\Live
comp_folder_2: M:\ChromatinTeam\Images_processing\20200526_Exp326_KSB_Elyra_DAPI_TADs_SIM_Live_fix_perm_HCl\Ibidi_2_SIM\Fixed
template_comp_1: 
    - 'DE_2'
template_comp_2: 
    - 'DE_2'
analysis_channels:
    - 0
    - 1
drift_correction_channel: 1

