#COM ports for pump and stage:
pump_port: COM6
stage_port: COM5

#Well plate setup:
well_plate:
    bottom_right:
      x: 108
      y: 72
    top_left:
      x: 0
      y: 0
    columns: 12
    rows: 8
    first_probe: A1
    last_probe: B12
    well_spacing: 9
    z_base: -36

#Positions outside of well plate
positions:
    SSC_DAPI:
      x: 20
      y: 100
      z: -37
    FA:
      x: 20
      y: 119
      z: -37

#The sequence to follow. Possible actions and parameters are probe: wp or position listed above, pump: time for pumping, pause: time for pause, image: 1.
sequence:
    - probe: wp
    - pause: 2
    - pump: 30
    - pause: 300
    - probe: FA_wash
    - pause: 2
    - pump: 30
    - probe: wp
    - pause: 2
    - pump: 30
    - image: 1


