#       PARAMETERS FOR IMAGE PROCESSING AND TRACING        #
# -------------------------------------------------------- #

#Path and file definitions:
input_path: XXXX    #File store (without extension) or folder
output_path: XXXX #Analysis folder
output_prefix: XXXX_                 #Prefix for output filenames.

image_filetype: zip                                 #Type of files. Options: zip, zarr, tif/tiff or czi.
image_template:                                     #If multiple tif/czi, substring template to match.
    - 'DE_2'

image_view_downscaling: 1                           #If downscaling (int) used when viewing images.         

#Imaging properties (used for calibration and deconvolution)
xy_nm: 97                                           #Camera pixel size [nm]
z_nm: 200                                           #Z-slice spacing
spot_wavelength: 590                                #Approximate emmision wavelength of FISH probe.
objective_na: 1.46                                  #Numerical aperture of objective

#Parameters for nucleus analysis
ilastik_path: XXX\run-ilastik.bat                   #(Optional) Path to ilastik
ilastik_project_path: XXX\ilastik_nucs_class.ilp    #(Optional) Path to ilastik object classification project.
nuc_diameter: 150                                   #Approximate diameter of nuclei in images [px]
nuc_dilation: 5                                     #How much to dilate nuclear masks after detection [px]
nuc_channel: 2                                      #The image channel (0-based) where nuclei are imaged.
nuc_ref_frame: 13                                   #Which image frame nuclei should be detected in.

#Fiducial parameters (NB! 0-based, also the timepoints):
bead_ch: 0                                          #The channel of the fiducial beads/marks                 
bead_reference_frame : 13                           #The frame used as reference of the drift correction
bead_threshold: 1000                                #Minimum intensity for bead detection
min_bead_intensity: 1500                            #Minimum intensity for bead segmentation
bead_points: 50                                     #Maximum number of beads to segment

#Tracing parameters (NB! 0-based, also the timepoints):
trace_ch: 1                                         #Which channel to peform tracing in
spot_frame: 12                                      #(Int or list) Frame(s) where spots are to be detected for segmentation. Tracing is done in all frames.
spot_threshold: 20                                  #On DoG image, usually set after previewing in GUI.
spot_downsample: 1                                  #Downsampling (int) for spot detection, not fitting.
spot_in_nuc: True                                   #Only filter for spots inside nuclear masks.
fit_func: LS                                        #Use LS or MLE solvers for spot fitting.
deconvolve: 30                                      #Number of deconvolution iterations, 0 is off.

#Size of region segmented around each detected spot for tracing:
roi_image_size:
    - 12
    - 16
    - 16
    
#           PARAMETERS FOR ANALYSIS POST TRACING           #
# -------------------------------------------------------- #
#Tracing QC parameters, will often need to be empirically determined:
A_to_BG: 2              #Minimum signal to background of gaussian fit to accept
sigma_xy_max: 100       #Maximum std in xy of gaussian fit [nm]
sigma_z_max: 250        #Maximum std in z of gaussian fit [nm]
max_dist: 300           #Maximum 3D distance from reference spot that a detected spot can be [nm]
dist_ref_frame: 13      #Frame to use for the distance reference spot above.

#List of barcodes/identifiers used in each of the imaging frames:
frame_name:
    - pre_image
    - D01
    - D02
    - D03
    - D04
    - D05
    - D06
    - D07
    - D08
    - D09
    - D10
    - D01_rep
    - blank
    - all